#!/usr/bin/env bash
# Script to display information about subdomains

# Function to fetch and display DNS information
fetch_and_display_dns() {
    local subdomain=$1
    local domain=$2

    # Performing the DNS lookup
    local dns_output=$(dig +noall +answer ${subdomain}.${domain} A | awk '{print $4, $5}')

    if [ -n "$dns_output" ]; then
        # Extract record type and IP
        local record_type=$(echo $dns_output | cut -d ' ' -f 1)
        local ip_address=$(echo $dns_output | cut -d ' ' -f 2)

        echo "The subdomain ${subdomain} is a ${record_type} record and points to ${ip_address}"
    else
        echo "No A record found for ${subdomain}.${domain}"
    fi
}

# Main function to process the arguments
process_arguments() {
    local domain=$1
    local subdomain=$2

    # Default subdomains
    local default_subdomains=("www" "lb-01" "web-01" "web-02")

    if [ -z "$domain" ]; then
        echo "*** Provide domain name ***"
        return 1
    fi

    if [ -z "$subdomain" ]; then
        # Loop through and display default subdomains
        for sd in "${default_subdomains[@]}"; do
            fetch_and_display_dns $sd $domain
        done
    else
        # Display information for the specified subdomain
        fetch_and_display_dns $subdomain $domain
    fi
}

# Call the main function with provided arguments
process_arguments $1 $2
