#!/usr/bin/env bash
# Script to display information about subdomains

# Function to fetch and display DNS information
fetch_and_display_dns() {
    local subdomain=$1
    local domain=$2
    local dns_output record_type ip_address

    # Performing the DNS lookup
    dns_output=$(dig +noall +answer "${subdomain}.${domain}" A | awk '{print $4, $5}')

    # Check if DNS output is non-empty and display formatted result
    if [ -n "$dns_output" ]; then
        record_type=$(echo "$dns_output" | cut -d ' ' -f 1)
        ip_address=$(echo "$dns_output" | cut -d ' ' -f 2)
        echo "The subdomain ${subdomain} is a ${record_type} record and points to ${ip_address}"
    fi
}

# Main function to process the arguments
process_arguments() {
    local domain=$1
    local subdomain=$2

    # Default subdomains
    local default_subdomains=("www" "lb-01" "web-01" "web-02")

    # If no subdomain is specified, loop through default subdomains
    if [ -z "$subdomain" ]; then
        for sd in "${default_subdomains[@]}"; do
            fetch_and_display_dns "$sd" "$domain"
        done
    else
        # Display information for the specified subdomain
        fetch_and_display_dns "$subdomain" "$domain"
    fi
}

# Call the main function with provided arguments
process_arguments "$1" "$2"
