#!/usr/bin/env bash
# This script installs and configures Nginx on an Ubuntu server and allows traffic on port 80

apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
