#!/usr/bin/env bash
# This script configures Nginx to redirect /redirect_me to another page with a 301 Moved Permanently response

# Ensure Nginx is installed
apt-get update -y
apt-get install nginx -y

# Add redirection configuration
REDIRECT_CONF="location \/redirect_me { return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4; }"
sed -i "/server_name _;/a $REDIRECT_CONF" /etc/nginx/sites-available/default

# Restart Nginx to apply changes (without using systemctl)
service nginx restart
