#!/usr/bin/env bash
# This script configures Nginx to display a custom 404 page

# Ensure Nginx is installed
sudo apt-get update -y
sudo apt-get install nginx -y

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html > /dev/null

# Add custom 404 configuration to Nginx
sudo sed -i '/server_name _;/a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes (without using systemctl)
sudo service nginx restart
