#!/usr/bin/env bash
# Install and configure HAProxy on the lb-01 server

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Backup the original HAProxy configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAProxy
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg' << EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 429887-web-01 54.164.215.149:80 check
    server 429887-web-02 100.25.16.145:80 check
EOF

# Restart HAProxy to apply changes
sudo service haproxy restart
