#!/usr/bin/env bash
# This script creates a MySQL dump of all databases and compresses it into a tar.gz archive.

# Check for MySQL password as an argument
if [ $# -eq 0 ]; then
    echo "Usage: $0 <MySQL-Root-Password>"
    exit 1
fi

# MySQL dump of all databases into a file named 'backup.sql'
mysqldump -uroot -p"$1" --all-databases > backup.sql

# Compress 'backup.sql' into a tar.gz archive with the current date as its name
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
