#!/usr/bin/env bash
# This script displays listening ports with the PID and name of the program to which each socket belongs

# Using netstat to get the required information
# We use the -l flag to display only listening sockets,
# the -n flag to show numerical addresses,
# the -t flag to display TCP connections,
# the -u flag to display UDP connections,
# the -p flag to show the PID and name of the program
netstat -lntup
