#!/usr/bin/env bash
# This script configures Nginx to listen on port 80 of all active IPv4 IPs

# Remove and recreate the symbolic link for Nginx default site
sudo rm -f /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx service
sudo service nginx restart
