#!/usr/bin/env bash
# Fixes Nginx to listen on port 80 and restarts the service
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
