#!/usr/bin/env bash
# Script to demonstrate process signaling and PID file management.

echo "$$" > /var/run/myscript.pid

trap 'echo "I hate the kill command";' SIGTERM
trap 'echo "Y U no love me?!"; exit 0;' SIGINT
trap 'rm /var/run/myscript.pid; exit 0;' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 1
done
