#!/usr/bin/env bash
# A script to handle the manage_my_process.

PID_FILE="/var/run/my_process.pid"

launch_process() {
    ./manage_my_process & 
    echo $! > "$PID_FILE"
    echo "manage_my_process has started."
}

terminate_process() {
    if [ -f "$PID_FILE" ]; then
        kill $(cat "$PID_FILE") && rm -f "$PID_FILE"
        echo "manage_my_process has been stopped."
    else
        echo "manage_my_process is not running."
    fi
}

restart_the_process() {
    terminate_process
    sleep 1
    launch_process
    echo "manage_my_process has restarted."
}

case "$1" in
    start)
        launch_process
        ;;
    stop)
        terminate_process
        ;;
    restart)
        restart_the_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
