#!/usr/bin/env bash
# Script to stop the 4-to_infinity_and_beyond process

# Find the PID of 4-to_infinity_and_beyond
PID=$(pgrep -f 4-to_infinity_and_beyond)

# If the process is found, kill it
if [ -n "$PID" ]; then
    kill "$PID"
    echo "4-to_infinity_and_beyond process with PID $PID has been terminated."
else
    echo "4-to_infinity_and_beyond process not found."
fi
