#!/usr/bin/env bash
# This script loops from 1 to 10. For the 4th iteration, it displays "bad luck", for the 8th "good luck", and "Best School" for the other iterations.

counter=1

while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]
    then
        echo "bad luck"
    elif [ $counter -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
