#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080

# Change Nginx user
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Change listening port with more specificity
sudo sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Set permissions
sudo chmod 644 /etc/nginx/nginx.conf

# Stop Apache if it's running
sudo pkill apache2

# Restart Nginx
sudo service nginx restart
