#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080

# Change Nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Change listening port with more specificity
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Set permissions
chmod 644 /etc/nginx/nginx.conf

# Stop Apache if it's running
pkill apache2

# Restart Nginx
sudo -u nginx service nginx restart
